# generated by datamodel-codegen:
#   filename:  records.json
#   timestamp: 2025-02-07T21:19:52+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, RootModel


class ModelItem(BaseModel):
    cdi_id: str
    year: int
    status: str
    pi_name: str
    title: str
    short_title: Optional[str] = None
    givenname: str
    surname: str
    pi_org: str
    pi_missionarea: str
    id: str


class Model(RootModel[List[ModelItem]]):
    root: List[ModelItem]
